server:
  servlet:
    context-path: /api/market-place
    application-display-name: Market Place
spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}:5432/${DB_NAME}?currentSchema=${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: MarketPlacePool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 2000000
      idle-timeout: 6000000
      max-lifetime: 18000000
      auto-commit: false
      leak-detection-threshold: 200000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: ${LIQUIBASE_ENABLED}
    default-schema: ${DB_SCHEMA}
    change-log: classpath:db/changelog/db.changelog-main.yaml


security:
  public-urls:
    - /auth/**
    - /swagger-ui/**
    - /auth/login
    - /auth/register
    - /auth/refresh
  jwt:
    secret: ${JWT_SECRET}
    access-exp: 360_000      # 5 min
    refresh-exp: 420_000     # 7 min