spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/market_place?currentSchema=online_shop
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: MarketPlacePool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 10000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: false
      leak-detection-threshold: 20000
  liquibase:
    default-schema: online_shop
    enabled: true

security:
  public-urls:
    - /auth/**
    - /swagger-ui/**
    - /auth/login
    - /auth/register
    - /auth/refresh
  jwt:
    secret: "CHANGE_TO_32+_CHAR_RANDOM_SECRET"
    access-exp: 360_000      # 5 min
    refresh-exp: 420_000     # 7 min