server:
  servlet:
    application-display-name: Market Place
spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}:5454/${DB_NAME}?currentSchema=${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: MarketPlacePool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 2000000
      idle-timeout: 6000000
      max-lifetime: 18000000
      auto-commit: false
      leak-detection-threshold: 200000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true