CREATE SCHEMA IF NOT EXISTS online_shop;

CREATE TABLE category
(
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(100) NOT NULL UNIQUE,
    description    VARCHAR(250),
    image          VARCHAR(250),
    parent_id      INT,
    category_order INT          NOT NULL default 1,
    is_active      boolean      NOT NULL default true,
    is_deleted     boolean      NOT NULL default false,
    created_at     TIMESTAMP    NOT NULL default CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL default CURRENT_TIMESTAMP
);

ALTER TABLE category
    ADD CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES category (id);


CREATE TABLE brand
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(250),
    image       VARCHAR(250),
    is_active   boolean      NOT NULL default true,
    is_deleted  boolean      NOT NULL default false,
    created_at  TIMESTAMP    NOT NULL default CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL default CURRENT_TIMESTAMP
);

CREATE TABLE item
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(250),
    image       VARCHAR(250),
    price       DECIMAL(10, 2),
    category_id INT,
    brand_id    INT,
    is_active   boolean      NOT NULL default true,
    is_deleted  boolean      NOT NULL default false,
    created_at  TIMESTAMP    NOT NULL default CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL default CURRENT_TIMESTAMP
);

ALTER TABLE item
    ADD CONSTRAINT fk_item_category FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE item
    ADD CONSTRAINT fk_item_brand FOREIGN KEY (brand_id) REFERENCES brand (id);



INSERT INTO brand(name,
                  description,
                  image)
VALUES ('Samsung',
        'Samsung electronics',
        'image1.jpg');


INSERT INTO brand(name,
                  description,
                  image)
VALUES ('Irshad',
        'Irshad electronics',
        'image2.jpg'),
       ('Kontakt',
        'Kontakt electronics',
        'image1.jpg');


INSERT INTO category(name,
                     description,
                     image,
                     parent_id,
                     category_order,
                     is_active,
                     is_deleted,
                     created_at,
                     updated_at)
VALUES ('Mobiles',
        'Mobiles category',
        'image1.jpg',
        null,
        1,
        true,
        false,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Smart phones',
        'Smart phone category',
        'image1.jpg',
        1,
        1,
        true,
        false,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Home appliances',
        'Home category',
        'image2.jpg',
        null,
        1,
        true,
        false,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);


INSERT INTO item(name,
                 description,
                 image,
                 price,
                 category_id,
                 brand_id)
VALUES ('Samsung Galaxy S20',
        'Samsung Galaxy S20',
        'image1.jpg',
        10000,
        1,
        1),
       ('Samsung Galaxy A53',
        'Samsung Galaxy A53',
        'image1.jpg',
        5000,
        1,
        1);


INSERT INTO item(name,
                 description,
                 image,
                 price,
                 category_id,
                 brand_id)
VALUES ('LG TV',
        'LG LG S20',
        'image1.jpg',
        10000,
        3,
        3),
       ('Sony',
        'Sony',
        'image1.jpg',
        800,
        1,
        1);

UPDATE brand
SET is_deleted = true,
    is_active  = false,
    name       = 'SAMSUNG Electronics'
WHERE id = 1;
